### ISSUE TITLE
 My AUTO IP Changer flagging error after changing of the first IP

### ISSUE THREAD

**Issue by Panacearica** [FDX100/Auto_Tor_IP_changer#1]
When I started the 
--"python3 autoTOR3.py" in the terminal, this is what I received
"""""
 *if you dont have tor . then you must install tor (sudo apt-get install tor , sudo apt-get install privoxy)

Failed to start tor.service: Unit tor.service is masked.
 change your  SOCKES to 127.0.0.1:9050 

Failed to start tor.service: Unit tor.service is masked.
time to change Ip in Sec [type=60] >>  """"""
then I specified the number of seconds it will take to change and the number of times I want it to change. 
After it successfully changed the first IP, this is what I briefly received in return

"""""
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/socks.py", line 832, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:
"""""
Any Help Guys, Because I have the TOR browser and the privoxy intalled already in the 2020 kali

**Comment by FDX100** [comment]
everything is fixed now you can use it if you try run it with root your problems will be fixed
