### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by javad-o** [FDX100/Auto_Tor_IP_changer#14]
In the name of God
hello, your tool gives me an error. I don't know if my internet is weak or if it's really like this for everyone

**Comment by somdipto** [comment]
> In the name of God hello, your tool gives me an error. I don't know if my internet is weak or if it's really like this for everyone

dude its working now i just tested this , if still not workin explain like which part is not working ,were are you getting stuck.
 i reffer u this vedio          https://youtu.be/QK4nPt3G3qc?si=rcxNVrGtw6G7asWy
 this will surely work ,on the name of god...

**Comment by Keskebeu** [comment]
All you are doing is connecting through a proxy man. Now whoever is behind that proxy can see  all your browsing info and metadata.

You are simply becoming an easy target. Read the code it's just a simple Python script running a simple command. I can't believe people fall for anything they see on the internet.
