### ISSUE TITLE
Error: Forbidden

### ISSUE THREAD

**Issue by harismehboob142** [FDX100/Auto_Tor_IP_changer#18]
change your  SOCKES to 127.0.0.1:9050 

[+] time to change Ip in Sec [type=60] >> 5
[+] how many time do you want to change your ip [type=1000]for infinte ip change type [0] >>10
[+] Your IP has been Changed to : 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/raw</code> from this server.</h2>
<h2></h2>
</body></html>

^CTraceback (most recent call last):
  File "/usr/share/aut/autoTOR.py", line 85, in <module>
    time.sleep(int(x))
KeyboardInterrupt

**Comment by 0PandaDEV** [comment]
i have the same issue

**Comment by Mayar111** [comment]
same issue 😞

**Comment by FDX100** [comment]
fixed
