### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by Code-With-Abhishek-Kumar** [FDX100/Auto_Tor_IP_changer#22]
[+] Your IP has been Changed to : 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/raw</code> from this server.</h2>
<h2></h2>
</body></html>

**Comment by FDX100** [comment]
fixed
