### ISSUE TITLE
unable to use aut

### ISSUE THREAD

**Issue by black-ka** [FDX100/Auto_Tor_IP_changer#23]
I have installed python and did all the steps still it shows command not found and pip3 not installed
![Screenshot_20240214_230206](https://github.com/FDX100/Auto_Tor_IP_changer/assets/83385587/0c2acfc6-3157-4108-8059-2c5f8c09712d)

**Comment by durontoo** [comment]
same problem

**Comment by FDX100** [comment]
fixed
