### ISSUE TITLE
Windows 10?

### ISSUE THREAD

**Issue by blakeboy01** [FDX100/Auto_Tor_IP_changer#3]
Is it possible to use this on Windows 10, if not is any other Tor ip changers I could use for Windows 10?

Thanks.

**Comment by seevik2580** [comment]
try to use WSL1/2 (Windows subsystem for linux) feature in windows. 
or if you dont want to use linux try this for windows [https://github.com/seevik2580/tor-ip-changer](https://github.com/seevik2580/tor-ip-changer)
