### ISSUE TITLE
error occure in change new ip address

### ISSUE THREAD

**Issue by rsnarsna** [FDX100/Auto_Tor_IP_changer#30]
+] Your IP has been Changed to :                                                
<html><head>                                                                     
<meta http-equiv="content-type" content="text/html;charset=utf-8">               
<title>403 Forbidden</title>                                                     
</head>                                                                          
<body text=#000000 bgcolor=#ffffff>                                              
<h1>Error: Forbidden</h1>                                                        
<h2>Your client does not have permission to get URL <code>/raw</code> from this server.</h2>                                                                      
<h2></h2>                                                                        
</body></html>                                                                   
                                                                                 
[+] Your IP has been Changed to :                                                
<html><head>                                                                     
<meta http-equiv="content-type" content="text/html;charset=utf-8">               
<title>403 Forbidden</title>                                                     
</head>                                                                          
<body text=#000000 bgcolor=#ffffff>                                              
<h1>Error: Forbidden</h1>                                                        
<h2>Your client does not have permission to get URL <code>/raw</code> from this server.</h2>                                                                      
<h2></h2>                                                                        
</body></html>                         

how to solve this error

**Comment by Vikaskumar8130** [comment]
Hii

**Comment by FDX100** [comment]
thanks for your report it's patched now
