### ISSUE TITLE
The code literally does nothing 🤣🤣🤣 nice joke

### ISSUE THREAD

**Issue by AndrexYT** [FDX100/Auto_Tor_IP_changer#36]

**Comment by FDX100** [comment]
it work you should give it a chance

**Comment by rawnullbyte** [comment]
> it work you should give it a chance

Bud, I am a python programmer, I ain't that dumb

**Comment by FDX100** [comment]
if you were a programmer you could notice that this script only perform a loop to manipulate tor proxy to change the ip address 😂😂😂😂

**Comment by rawnullbyte** [comment]
Oh it just reloads tor service 💀 there are few issues:
1. Too slow 
2. Will work only on linux
