### ISSUE TITLE
error to change IP

### ISSUE THREAD

**Issue by QairexStudio** [FDX100/Auto_Tor_IP_changer#4]
hi bro. i have problem to change the ip adress:
`time to change Ip in Sec [type=60] >> 1                                                                                     
how many time do you want to change your ip [type=1000]for infinte ip change type [0] >>0                                   
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5                                                     
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5                                                     
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5                                                     
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5                                                     
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5                                                     
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5                                                     
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5                                                     
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5                                                     
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5                                                     
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5                                                     
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5                                                     
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5                                                     
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5                                                     
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5                                                     
<<<<<<<<<<<<<<<<Your IP has been Changed>>>>>>>>>>>>>>>>> 185.220.101.5 ` but my ip adress cannot changing... why?

**Comment by FDX100** [comment]
you have to change your system proxy for example if you want your browser to change go to setting of your browser change proxy socks5 to 127.0.0.1 port 9050
or use 
apt install proxychanins 
then run applications like this
proxychains firefox
at same time you have to run autoTor
or just watch this 
https://www.youtube.com/watch?v=Hi7sRyGGORA
